devpass-tech/challenge-tests-finance

solutions/devsprint-caio-santos-2/FinanceApp.xcodeproj/project.pbxproj, solutions/devsprint-caio-santos-2/FinanceApp.xcworkspace/contents.xcworkspacedata, solutions/devsprint-caio-santos-2/FinanceApp.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, solutions/devsprint-caio-santos-2/Podfile, solutions/devsprint-caio-santos-2/Podfile.lock
- Integrado a biblioteca snapshotTesting
=> add snapshotTesting library

solutions/devsprint-caio-santos-2/FinanceApp.xcodeproj/project.pbxproj, solutions/devsprint-caio-santos-2/FinanceApp.xcodeproj/xcshareddata/xcschemes/FinanceApp.xcscheme, solutions/devsprint-caio-santos-2/FinanceApp.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings, solutions/devsprint-caio-santos-2/FinanceAppTests/UserProfileTests.swift, solutions/devsprint-caio-santos-2/FinanceAppUITests/FinanceAppUITests.swift
------------ APAGAR ------------
Emojis para os titulos dos MR's
* ✨ - Introduce new features
* 🚧 - Work in progress
More on: https://gitmoji.dev
------------ APAGAR ------------
=> Implementar Teste Unitário para método formattedAgency

solutions/devsprint-caio-santos-2/FinanceApp.xcodeproj/project.pbxproj, solutions/devsprint-caio-santos-2/FinanceApp.xcodeproj/xcshareddata/xcschemes/FinanceApp.xcscheme, solutions/devsprint-caio-santos-2/FinanceAppTests/ClassIdentifierTests.swift
- Implementado o teste unitário para a função que retorna o identificador para uma UITableViewCell.
| iPhone 11|
=> Unit test classIdentifier

solutions/devsprint-caio-santos-2/FinanceAppTests/UserProfileTests.swift
------------ APAGAR ------------
Emojis para os titulos dos MR's
* ✨ - Introduce new features
* 🚧 - Work in progress
More on: https://gitmoji.dev
------------ APAGAR ------------
=> testando o metodo formattedAccount

solutions/devsprint-caio-santos-2/FinanceAppTests/RemoveSpaceTests.swift
------------ APAGAR ------------
Emojis para os titulos dos MR's
* ✨ - Introduce new features
* 🚧 - Work in progress
More on: https://gitmoji.dev
------------ APAGAR ------------
- [] Não adiciona código duplicado
- [] Não contém código comentado
- [] Não contém código WIP
=> Remove Space Test

solutions/devsprint-caio-santos-2/FinanceApp.xcodeproj/project.pbxproj, solutions/devsprint-caio-santos-2/FinanceApp/Service/FinanceService.swift, solutions/devsprint-caio-santos-2/FinanceAppTests/FinanceServiceTests.swift, solutions/devsprint-caio-santos-2/FinanceAppTests/Mock/FinanceServiceMock.swift, solutions/devsprint-caio-santos-2/FinanceAppTests/Mock/TransferAmount/NetworkClientTransferAmountMockError.swift, solutions/devsprint-caio-santos-2/FinanceAppTests/Mock/TransferAmount/NetworkClientTransferAmountMockNil.swift, solutions/devsprint-caio-santos-2/FinanceAppTests/Mock/TransferAmount/NetworkClientTransferAmountMockSuccess.swift, solutions/devsprint-caio-santos-2/FinanceAppUITests/FinanceAppUITests.swift
=>  ✨ Adding sample UITests and adjusting files and method names.

solutions/devsprint-caio-santos-2/FinanceApp.xcodeproj/project.pbxproj, solutions/devsprint-caio-santos-2/FinanceApp/AppDelegate/SceneDelegate.swift, solutions/devsprint-caio-santos-2/FinanceApp/Extensions/String+Extensions.swift, solutions/devsprint-caio-santos-2/FinanceApp/Modules/CreateAccount/CreateAccountConfigurator.swift, solutions/devsprint-caio-santos-2/FinanceApp/Modules/CreateAccount/CreateAccountInteractor.swift, solutions/devsprint-caio-santos-2/FinanceApp/Modules/CreateAccount/CreateAccountPresenter.swift, solutions/devsprint-caio-santos-2/FinanceApp/Modules/CreateAccount/CreateAccountProtocols.swift, solutions/devsprint-caio-santos-2/FinanceApp/Modules/CreateAccount/CreateAccountRouter.swift, solutions/devsprint-caio-santos-2/FinanceApp/Modules/CreateAccount/CreateAccountViewController.swift, solutions/devsprint-caio-santos-2/FinanceApp/Modules/Login/LoginConfigurator.swift, solutions/devsprint-caio-santos-2/FinanceApp/Modules/Login/LoginInteractor.swift, solutions/devsprint-caio-santos-2/FinanceApp/Modules/Login/LoginPresenter.swift, solutions/devsprint-caio-santos-2/FinanceApp/Modules/Login/LoginProtocols.swift, solutions/devsprint-caio-santos-2/FinanceApp/Modules/Login/LoginRouter.swift, solutions/devsprint-caio-santos-2/FinanceApp/Modules/Login/LoginViewController.swift
=> ✨ New login modules in viper architecture.

solutions/devsprint-caio-santos-2/FinanceApp.xcodeproj/project.pbxproj, solutions/devsprint-caio-santos-2/FinanceAppTests/FinanceServiceTests.swift, solutions/devsprint-caio-santos-2/FinanceAppTests/Mock/UserProfile/FileNetworkClientUserProfiletMockError.swift, solutions/devsprint-caio-santos-2/FinanceAppTests/Mock/UserProfile/NetworkClientUserProfiletMockError.swift, solutions/devsprint-caio-santos-2/FinanceAppTests/Mock/UserProfile/NetworkClientUserProfiletMockSuccess.swift
Realizo teste unitário para testar o método fetchUserProfile()
=> adicionado teste para fetchUserProfile()

solutions/devsprint-vinicius-carvalho-2/FinanceApp.xcodeproj/project.pbxproj, solutions/devsprint-vinicius-carvalho-2/FinanceAppTests/String+ExtensionsTests.swift
Added unit tests to cover String+Extensions file.
Decrease iOS deployment version to 13.0.
=> :white_check_mark: add string extension unit tests

solutions/devsprint-vinicius-carvalho-2/FinanceApp.xcodeproj/project.pbxproj, solutions/devsprint-vinicius-carvalho-2/FinanceAppTests/UITableViewCell+ExtensionsTests.swift
Added unit tests to cover TableViewCell classIdentifier extension method.
=> ✅  add class identifier unit tests

solutions/devsprint-julio-fernandes-2/Podfile
=> ✨ Adding the pod SnapshotTesting

README.md, Scripts/setup
Adicionando arquivo de script para que seja mais fácil criar o projeto base, já que estamos usando o XcodeGen como ferramenta para criar nosso .xcodeproj e .xcworkspace
```
brew install xcodegen
```
```
cd Scripts && ./setup open
```
=> ✨Adicionando script para configuração do projeto FinanceApp

README.md, Scripts/setup, solutions/devsprint-julio-fernandes-2/FinanceAppTests/HomeDataTests.swift
Testes unitários do método formattedInfo.
=> feat: add unitary tests to formattedInfo method

solutions/devsprint-julio-fernandes-2/FinanceAppTests/UITableViewCellTests.swift
adicionado teste do metodo classIdentifier()
=> Teste do método classIdentifier() - Sprint Julio

solutions/devsprint-julio-fernandes-2/FinanceApp/Extensions/String+Extensions.swift, solutions/devsprint-julio-fernandes-2/FinanceAppTests/removingSpacesTest.swift
Adiciona testes da Extension String (removingSpaces)
- [] Não contém código WIP
=> Removing spaces test

solutions/devsprint-julio-fernandes-2/FinanceAppUITests/ProfileUITests.swift
Teste de UI para navegação entre Home e Profile.
=> feat: add UI tests for navigation home to profile

solutions/devsprint-julio-fernandes-2/FinanceAppUITests/ConfirmationUITests.swift
Teste de UI para navegação entre Transfer e Confirmation.
=> feat: add UI tests for navigation transfers to confirmation

solutions/devsprint-julio-fernandes-2/FinanceAppTests/FinanceServiceTest.swift, solutions/devsprint-julio-fernandes-2/FinanceAppTests/Mock/NetworkClientTransferAmountMockError.swift, solutions/devsprint-julio-fernandes-2/FinanceAppTests/Mock/NetworkClientTransferAmountMockSuccess.swift
=> method  test transferAmount()-Sprint-Julio

solutions/devsprint-eduardo-bocato-2/FinanceApp.xcodeproj/project.pbxproj, solutions/devsprint-eduardo-bocato-2/FinanceAppTests/UIViewControllerExtensionTests.swift
Adds tests to UIViewController+Extension class
=> ✨ [Bocato] UIViewController+Extension tests

solutions/devsprint-attekita-3/FinanceApp.xcodeproj/project.pbxproj, solutions/devsprint-attekita-3/FinanceApp.xcworkspace/contents.xcworkspacedata, solutions/devsprint-attekita-3/FinanceApp.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, solutions/devsprint-attekita-3/Podfile
=> Adding the snapshot pod

solutions/devsprint-eduardo-bocato-2/FinanceApp.xcodeproj/project.pbxproj, solutions/devsprint-eduardo-bocato-2/FinanceApp/Core/Services/Entities/Contact.swift, solutions/devsprint-eduardo-bocato-2/FinanceApp/Core/Services/Entities/TransferResult.swift, solutions/devsprint-eduardo-bocato-2/FinanceApp/Scenes/Transfers/Domain/TransferMoneyUseCase.swift, solutions/devsprint-eduardo-bocato-2/FinanceApp/Scenes/Transfers/TransfersViewModel.swift, solutions/devsprint-eduardo-bocato-2/FinanceAppTests/Helpers/PublisherCollector.swift, solutions/devsprint-eduardo-bocato-2/FinanceAppTests/Scenes/Transfers/TransfersViewModelTests.swift
Creates the tests for TransfersViewModel
=> [Bocato] Create TransfersViewModel tests

solutions/devsprint-attekita-3/FinanceApp/Service/FinanceService.swift
Improvements in FinanceService class.
Add a generic decodeJson method that return the decoded data with the specific type, if fails returns nil.
Adjusts the fetch methods to use this decodeJson method.
Create the URLString enum with the URLs to fetch API.
=> Improvements in FinanceService class

solutions/devsprint-attekita-3/FinanceApp.xcodeproj/project.pbxproj, solutions/devsprint-attekita-3/FinanceAppTests/Service/StringExtensionTest.swift
Adiciona teste para o metodo removeSpace()
=> [Sprint-Attekita] Add test for removeSpace()

solutions/devsprint-attekita-3/FinanceApp.xcodeproj/project.pbxproj, solutions/devsprint-attekita-3/FinanceApp.xcodeproj/xcshareddata/xcschemes/FinanceApp.xcscheme, solutions/devsprint-attekita-3/FinanceAppTests/Mocks/user_profile_endpoint.json, solutions/devsprint-attekita-3/FinanceAppTests/Service/FinanceServiceTests.swift
Implementing profile unit testing
=>  ✨ - Adding profile test

solutions/devsprint-attekita-3/FinanceApp.xcodeproj/project.pbxproj, solutions/devsprint-attekita-3/FinanceAppTests/Mocks/NetworkClientMock.swift, solutions/devsprint-attekita-3/FinanceAppTests/Mocks/home_endpoint.json, solutions/devsprint-attekita-3/FinanceAppTests/Service/FinanceServiceTests.swift
Implementação de testes para método do serviço chamado fetchHomeData. Um teste verifica se veio nil e outro se request ocorreu tudo certo.
- [] Não contém código comentado
=> ✨ Implement tests for fetch home data

solutions/devsprint-attekita-3/FinanceApp.xcodeproj/project.pbxproj, solutions/devsprint-attekita-3/FinanceApp/Service/ApiError.swift, solutions/devsprint-attekita-3/FinanceApp/Service/FinanceService.swift, solutions/devsprint-attekita-3/FinanceApp/Service/NetworkClient.swift, solutions/devsprint-attekita-3/FinanceAppTests/Mocks/NetworkClientMock.swift, solutions/devsprint-attekita-3/FinanceAppTests/Mocks/TransferAmount/transfer_amount_endpoint_false.json, solutions/devsprint-attekita-3/FinanceAppTests/Mocks/TransferAmount/transfer_successful_endpoint.json, solutions/devsprint-attekita-3/FinanceAppTests/Service/FinanceServiceTests.swift
Criação dos testes do método TransferAmount da classe FinanceService, testando se a requisição com dados mockados em um JSON executa corretamente. Além disso, foi refatorada a classe NetworkClient e NetworkClientMock, utilizando a classe Result no completion handler, e permitindo o uso de arquivos JSON personalizados para cada teste.
Todos os testes já existentes também rodaram com a modificação da camada de Network.
=> ✨ Transfer amount tests and NetworkClient refactor

solutions/devsprint-caio-santos-4/FinanceApp.xcodeproj/project.pbxproj, solutions/devsprint-caio-santos-4/FinanceAppTests/Service/Entities/AccountTests.swift
Incluir teste da função formattedAccount no arquivo UserProfile.swift 
=> ✨ Add test for Formatted Account Method

solutions/devsprint-caio-santos-4/FinanceApp.xcodeproj/project.pbxproj, solutions/devsprint-caio-santos-4/FinanceAppTests/Extensions/TableViewCellExtensionsTests.swift
=> ✨ Teste unitário para o método classIdentifier

solutions/devsprint-caio-santos-5/FinanceAppTests/Service/Entities/ActivityTests.swift
Implementação dos testes da Activity
=> ✨ Added Activity tests

solutions/devsprint-caio-santos-5/FinanceApp/Service/Entities/HomeData.swift, solutions/devsprint-caio-santos-5/FinanceAppTests/Service/FinanceServiceTests.swift, solutions/devsprint-caio-santos-5/FinanceAppTests/Service/Mock/HomeDataJsonData.swift, solutions/devsprint-caio-santos-5/FinanceAppTests/Service/Mock/NetworkClientMock.swift
- criado mock para networkClass 
- criado mock para json do home data
- criados testes para o fetch do homeData
=> ✨ - criados testes para home data

solutions/devsprint-caio-santos-5/FinanceApp/Service/Entities/ActivityDetails.swift, solutions/devsprint-caio-santos-5/FinanceAppTests/Service/FinanceServiceTests.swift, solutions/devsprint-caio-santos-5/FinanceAppTests/Service/Mock/ActivityDetailsJsonData.swift
Implementação dos testes do método fetchActivityDetails da FinanceService
=> ✨  Implementar Teste Unitário para método fetchActivityDetails

solutions/devsprint-caio-santos-5/FinanceApp/Service/FinanceService.swift, solutions/devsprint-caio-santos-5/FinanceAppTests/Service/FinanceServiceTests.swift, solutions/devsprint-caio-santos-5/FinanceAppTests/Service/Fixture/Activity+Fixture.swift, solutions/devsprint-caio-santos-5/FinanceAppTests/Service/Fixture/ActivityDetails+Fixture.swift, solutions/devsprint-caio-santos-5/FinanceAppTests/Service/Fixture/Contact+Fixture.swift, solutions/devsprint-caio-santos-5/FinanceAppTests/Service/Fixture/HomeData+Fixture.swift
criado teste para validar falha na criação da url 
fixtures movidas para seu proprio arquivo
=> ✨ - update service tests

solutions/devsprint-caio-santos-5/FinanceApp/Modules/Home/HomeViewModel.swift, solutions/devsprint-caio-santos-5/FinanceAppTests/Modules/FakeAPI/FakeFinanceService.swift, solutions/devsprint-caio-santos-5/FinanceAppTests/Modules/FakeAPI/FetchHomeDataResponse.swift, solutions/devsprint-caio-santos-5/FinanceAppTests/Modules/Home/HomeViewModelTests.swift
Implementação dos testes do método fetchData da HomeViewModel
criação da FakeAPI
criação da response da fetchData da FakeAPI.
=> ✨ Implementar Teste Unitário para método fetchData da HomeViewModel

solutions/devsprint-leonardo-santos-1/FinanceApp.xcodeproj/project.pbxproj, solutions/devsprint-leonardo-santos-1/FinanceAppTests/AccountTest.swift
Testar o método formattedAccount no model Agency 
=> Testing formattedAgency from Account Model

solutions/devsprint-julio-fernandes-2/FinanceAppTests/Service/Entities/ActivityTests.swift, solutions/devsprint-julio-fernandes-2/FinanceAppTests/Service/Entities/HomeDataUnitTests.swift
Adiciona teste unitário para o método formattedInfo
=> ✨ Adiciona teste unitário para o método formattedInfo

solutions/devsprint-leonardo-santos-1/FinanceAppTests/Service/Entities/UserProfileTest.swift
Adiciona teste da função formattedAcount da struct UserProfile
=> ✨- unity test of formattedAccount function

solutions/devsprint-leonardo-santos-1/FinanceApp.xcodeproj/project.pbxproj, solutions/devsprint-leonardo-santos-1/FinanceAppTests/NetworkClientSpy.swift
Adicionada classe NetworkClientSpy.
=> ✨ - Network Client Spy

solutions/devsprint-leonardo-santos-1/FinanceApp.xcodeproj/project.pbxproj, solutions/devsprint-leonardo-santos-1/FinanceApp/Service/FinanceService.swift, solutions/devsprint-leonardo-santos-1/FinanceAppTests/TransferAmountTests.swift
Cria um protocol novo para o transferAmount
Cria testes para o metodo transferAmount
=> ✨ Adiciona testes unitários para o método transferAmount

solutions/devsprint-leonardo-santos-1/FinanceApp.xcodeproj/project.pbxproj, solutions/devsprint-leonardo-santos-1/FinanceAppTests/Factories/DemoUseCaseFactoryTests.swift, solutions/devsprint-leonardo-santos-1/FinanceAppTests/Mirror+Extension.swift
Criação dos testes para a classe DemoUserCaseFactory
=> ✨ - DemoUserCaseFactoryTests

solutions/devsprint-leonardo-santos-1/FinanceApp.xcodeproj/project.pbxproj, solutions/devsprint-leonardo-santos-1/FinanceAppTests/Helpers/Fixtures.swift, solutions/devsprint-leonardo-santos-1/FinanceAppTests/Modules/ActivityDetails/ActivityDetailsViewModelTests.swift, solutions/devsprint-leonardo-santos-1/FinanceAppTests/Modules/ActivityDetails/NetworkingClientMock.swift
Adicionada classe de teste para ActivityDetailViewModel.
=> ✨ - ActivityDetailViewModelTests

solutions/devsprint-cecilia-saraiva-2/FinanceApp.xcodeproj/project.pbxproj, solutions/devsprint-cecilia-saraiva-2/FinanceAppTests/Extensions/Strings+ExtensionsTests.swift
=> create test removing space

solutions/devsprint-cecilia-saraiva-2/FinanceApp.xcodeproj/project.pbxproj, solutions/devsprint-cecilia-saraiva-2/FinanceApp.xcworkspace/contents.xcworkspacedata, solutions/devsprint-cecilia-saraiva-2/FinanceApp.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, solutions/devsprint-cecilia-saraiva-2/Podfile, solutions/devsprint-cecilia-saraiva-2/Podfile.lock
Inserted SnapShotTesting to project
=> Feature/ SnapShotTesting lib inserted

solutions/devsprint-leonardo-santos-3/FinanceAppTests/Extensions/UITableViewCellExtensionsTests.swift
Implement classIdentifier tests of UITableViewExtensions; 
N/A
=> ✨ - Implement classIdentifier tests

solutions/devsprint-leonardo-santos-3/FinanceAppTests/TestUtils/Doubles/NetworkClientSpy.swift
Implements a basic NetworkClientSpy with url, completionData and performRequestCount properties
=> ✨: Create NetworkClientSpy

solutions/devsprint-leonardo-santos-3/FinanceAppTests/Services/Entities/AccountTests.swift
Implementar Teste Unitário para método formattedAgency
Tests:
- test_formattedAgency_thenReturnAgencyFormatted
=> ✨ - AccountTests tests

solutions/devsprint-leonardo-santos-3/FinanceAppTests/Extensions/StringExtensionsTests.swift
Implementa a StringExtensionsTests
=> Strings removing spaces

solutions/devsprint-leonardo-santos-3/FinanceApp.xcodeproj/project.pbxproj, solutions/devsprint-leonardo-santos-3/FinanceApp/Service/Entities/Activity.swift, solutions/devsprint-leonardo-santos-3/FinanceApp/Service/Entities/HomeData.swift, solutions/devsprint-leonardo-santos-3/FinanceAppTests/Services/FinanceServiceTests.swift, solutions/devsprint-leonardo-santos-3/FinanceAppTests/TestUtils/Fixtures/Activity+Fixture.swift, solutions/devsprint-leonardo-santos-3/FinanceAppTests/TestUtils/Fixtures/HomeData+Fixture.swift
Add unit tests to `fetchHomeData` method.
=> Fetch home data tests

solutions/devsprint-leonardo-santos-3/FinanceAppTests/UseCases/GetRandomNumberUseCaseTests.swift
Adicionar Testes Unitários para GetRandomNumberUseCase
=> ✨ - Get Random Number Use Case tests

solutions/devsprint-leonardo-santos-3/FinanceApp/Modules/ActivityDetails/ActivityDetailsViewModel.swift, solutions/devsprint-leonardo-santos-3/FinanceAppTests/Modules/ActivityDetails/ActivityDetailsViewModelTests.swift, solutions/devsprint-leonardo-santos-3/FinanceAppTests/TestUtils/Doubles/ActivityDetailsViewModelDelegateSpy.swift, solutions/devsprint-leonardo-santos-3/FinanceAppTests/TestUtils/Doubles/FinanceServiceSpy.swift
Adiciona Testes Unitários para a ActivityDetailsViewModel
=> ✨ - Creating unit tests to ActivityDetailsViewModel

solutions/devsprint-rafael-de-paula-2/FinanceAppTests/StringExtensionsTests.swift
Created unit teste for removing spaces method of the string extension class
=> Created tests for removing spaces of the string extension class.

solutions/devsprint-rafael-de-paula-2/FinanceAppTests/HomeDataTests.swift
Created unit test for formatted info method for HomeData class.
=> Created test for formatted info method.

solutions/devsprint-rafael-de-paula-2/FinanceApp.xcodeproj/project.pbxproj, solutions/devsprint-rafael-de-paula-2/FinanceApp/Extensions/String+Extensions.swift, solutions/devsprint-rafael-de-paula-2/FinanceAppTests/Service/Doubles/Fixtures/Activity+Fixture.swift, solutions/devsprint-rafael-de-paula-2/FinanceAppTests/Service/Doubles/Fixtures/HomeData+Fixtures.swift, solutions/devsprint-rafael-de-paula-2/FinanceAppTests/Service/FinanceServiceTests.swift
=> Add fixtures

solutions/devsprint-brq-testes-ios-1/FinanceAppTests/Test Doubles/NetworkClientSpy.swift
=> Criação do NetworkClientSpy
